/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Student;
import  model.KRS;
import model.Course;
import model.Lecturer;
import java.util.ArrayList;
import controller.StudentController;
import controller.CourseController;
import controller.KRSController;
import controller.LecturerController;
import java.util.List;
import java.sql.SQLException;
import java.lang.System.Logger;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * 
 *
 * @author Henryy
 */
public class KRSForm extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KRSForm.class.getName());
    
    private String selectedNIM;
    ArrayList<Student>listMahasiswa = new ArrayList<>();
    List<Course>listMK = new ArrayList<>();
    List<Lecturer>listLecturer = new ArrayList<>();
    
    DefaultComboBoxModel<Student> comboModelMhs = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<Course> comboModelCourse = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<Lecturer> comboModelLecturer = new DefaultComboBoxModel<>();
    
    StudentController controller = new StudentController();
    CourseController courseController = new CourseController();
    LecturerController controllerLecturer = new  LecturerController();
    KRSController kRSController = new KRSController();
    
    
    /**
     * Creates new form KRSForm
     */
    public KRSForm() {
        initComponents();
        listMahasiswa = (ArrayList<Student>) controller.getstudent();
        listLecturer =  controllerLecturer.getLecturer();
        listMK = courseController.getAll();
        
        for(Lecturer lecturer : listLecturer){
            comboModelLecturer.addElement(lecturer);
        }
        for(Student student : listMahasiswa){
            comboModelMhs.addElement(student);
        }
        for(Course course : listMK){
            comboModelCourse.addElement(course);
        };
        
        try{
            loadKrsData();
        }catch(SQLException ex){
            ex.printStackTrace();
        }
    }
        private void loadKrsData() throws SQLException{
            List<KRS> krs = kRSController.getKrs();
            String[][] data = new String[krs.size()][6];
        
        for (int i=0; i < krs.size(); i++){
            data[i][0] = krs.get(i).getcourse().getCourseName();
            data[i][1] = krs.get(i).getstudent().getName();
            data[i][2] = krs.get(i).getLecturer().getName();
            data[i][3] = String.valueOf(krs.get(i).getsemester());
            data[i][4] = String.valueOf(krs.get(i).getScore());
            data[i][5] = krs.get(i).getGrade();
        }
        String[] columnName = {"Matakuliah","Mahasiswa","Dosen","Semester", "Score", "Grade"};
        jTable1.setModel(new javax.swing.table.DefaultTableModel(data, columnName));
    }
       private void clearForm(){
           jTextFieldScore.setText("");
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonBatal = new javax.swing.JButton();
        jButtonDELETE = new javax.swing.JButton();
        jButtonSIMPAN = new javax.swing.JButton();
        jComboBoxCodeMK = new javax.swing.JComboBox<>();
        jComboBoxNimMhs = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxnidn = new javax.swing.JComboBox<>();
        jLabelo = new javax.swing.JLabel();
        jTextFieldScore = new javax.swing.JTextField();
        jLabelsemester = new javax.swing.JLabel();
        jLabelgrade = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Kode matakuliah");

        jLabel3.setText("Nim Mahasiswa");

        jLabel4.setText("Semester");

        jLabel5.setText("Score");

        jButtonBatal.setText("BATAL");
        jButtonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatalActionPerformed(evt);
            }
        });

        jButtonDELETE.setText("DELETE");
        jButtonDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDELETEActionPerformed(evt);
            }
        });

        jButtonSIMPAN.setText("SIMPAN");
        jButtonSIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSIMPANActionPerformed(evt);
            }
        });

        jComboBoxCodeMK.setModel(comboModelCourse);
        jComboBoxCodeMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCodeMKActionPerformed(evt);
            }
        });

        jComboBoxNimMhs.setModel(comboModelMhs);
        jComboBoxNimMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNimMhsActionPerformed(evt);
            }
        });

        jLabel6.setText("NIDN Dosen");

        jComboBoxnidn.setModel(comboModelLecturer);

        jLabelo.setText("Grade");

        jTextFieldScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldScoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxNimMhs, 0, 129, Short.MAX_VALUE)
                            .addComponent(jComboBoxCodeMK, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxnidn, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jTextFieldScore, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabelsemester))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelgrade)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(jButtonBatal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jButtonDELETE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSIMPAN)
                        .addGap(30, 30, 30))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxCodeMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelsemester))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxNimMhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxnidn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelo)
                        .addComponent(jLabelgrade)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSIMPAN)
                    .addComponent(jButtonBatal)
                    .addComponent(jButtonDELETE))
                .addGap(14, 14, 14))
        );

        jLabel1.setText("MASTER KRS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_jButtonBatalActionPerformed

    private void jComboBoxCodeMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCodeMKActionPerformed
    Course course = (Course) jComboBoxCodeMK.getSelectedItem();
    if(course != null){
        jLabelsemester.setText(String.valueOf(course.getsemester()));
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCodeMKActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectedRow = jTable1.getSelectedRow();
        if(selectedRow !=-1){
            jComboBoxCodeMK.setSelectedItem(jTable1.getValueAt(selectedRow, 0).toString());
            jComboBoxNimMhs.setSelectedItem(jTable1.getValueAt(selectedRow, 1).toString());
            jComboBoxnidn.setSelectedItem(jTable1.getValueAt(selectedRow, 2).toString());
            jLabelsemester.setText(jTable1.getValueAt(selectedRow, 3).toString());
            jTextFieldScore.setText(jTable1.getValueAt(selectedRow, 4).toString());
            jLabelgrade.setText(jTable1.getValueAt(selectedRow, 5).toString());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBoxNimMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNimMhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNimMhsActionPerformed

    private void jButtonSIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSIMPANActionPerformed
        // TODO add your handling code here:
        Course course = (Course)jComboBoxCodeMK.getSelectedItem();
        Student student = (Student)jComboBoxNimMhs.getSelectedItem();
        Lecturer lecturer = (Lecturer)jComboBoxnidn.getSelectedItem();
        
        String scoreText = jTextFieldScore.getText();
        if(course == null || lecturer == null || scoreText.isEmpty()){
            
            JOptionPane.showMessageDialog(this,
                    "Please fill in all fields",
                    "Inpur Eror",
                    JOptionPane.ERROR_MESSAGE);
        }else{
             double score = Double.parseDouble(scoreText);
             
             int semester = course.getsemester();
             
             KRS krs = new KRS(course, score, "", lecturer, semester, student);
             jLabelgrade.setText(krs.getGrade());
             try{

            int res;

            
            if(selectedNIM != null){
                res = kRSController.update(krs, selectedNIM);
            }else{
                res = kRSController.create(krs);
            }

            if(res == 1){

                JOptionPane.showMessageDialog(this,
                        "KRS Saved Successfully",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);

                clearForm();
                loadKrsData();

            }else{

                JOptionPane.showMessageDialog(this,
                        "Error occurred while saving data",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }

        }catch(SQLException ex){

            JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
        
    }//GEN-LAST:event_jButtonSIMPANActionPerformed

    private void jButtonDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDELETEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDELETEActionPerformed

    private void jTextFieldScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldScoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KRSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KRSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KRSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KRSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KRSForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBatal;
    private javax.swing.JButton jButtonDELETE;
    private javax.swing.JButton jButtonSIMPAN;
    private javax.swing.JComboBox<Course> jComboBoxCodeMK;
    private javax.swing.JComboBox<Student> jComboBoxNimMhs;
    private javax.swing.JComboBox<Lecturer> jComboBoxnidn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelgrade;
    private javax.swing.JLabel jLabelo;
    private javax.swing.JLabel jLabelsemester;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldScore;
    // End of variables declaration//GEN-END:variables
}
